dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'org.libtorrent4j:libtorrent4j:2.1.0-38'
    implementation 'org.libtorrent4j:libtorrent4j-android-arm64:2.1.0-38'
    implementation 'org.libtorrent4j:libtorrent4j-android-arm:2.1.0-38'
    
    // VLC Player
    implementation 'org.videolan.android:libvlc-all:3.5.1'
}