name: Build APK

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
    
    - name: Clean old builds
      run: |
        rm -rf /home/runner/.gradle/caches/
        rm -rf /home/runner/work/meu-player/meu-player/.gradle/
        rm -rf /home/runner/work/meu-player/meu-player/app/build/
    
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    
    - name: Clean project
      run: ./gradlew clean
    
    - name: Build debug APK
      run: ./gradlew assembleDebug
    
    - name: Upload APK as Artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-debug
        path: app/build/outputs/apk/debug/*.apk
